version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: backend:latest
    working_dir: /app
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb+srv://hank:escanor77%40@cluster0.n62c5un.mongodb.net/
      - PORT=5001
      - JWT_SECRET=verysecret
    command: ["node", "server.js"]

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: frontend:latest
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]
